name: Build and Deploy
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Deploy React to GitHub Pages
      uses: bitovi/github-actions-react-to-github-pages@v1.2.2
      with:
         path: dist
         install_command: npm install
         build_command: npm run build
          
